# Generated by Django 5.1.3 on 2024-11-07 12:02

from django.db import migrations


def add_default_statuses(apps, schema_editor):
    TaskStatus = apps.get_model("classifiers", "TaskStatus")
    TaskStatus.objects.bulk_create(
        [
            TaskStatus(id=1, name="Выполнено"),
            TaskStatus(id=2, name="Не выполнено"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("classifiers", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_default_statuses),
    ]
